title: Soup
author: pink
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Soup is best for health, I love soup.
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
